# This is a basic workflow that is manually triggered

name: Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Copy repository
      - uses: actions/checkout@v2
      
      - name: Use NodeJS ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
      - with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
      - uses: borales/actions-yarn@v3.0.0
      - with:
          cmd: install
          
      - name: Lint project
      - uses: borales/actions-yarn@v3.0.0
      - with:
          cmd: lint
          
      - name: Run test
      - uses: borales/actions-yarn@v3.0.0
      - with:
          cmd: test
